name: opennebula

x-common-volumes: &common-volumes
  volumes:
    - /var/lib/one:/var/lib/one
    - /var/log/one:/var/log/one
    - /etc/one:/etc/one
    - /run/lock/one:/run/lock/one
    - /run/one:/run/one
    - /etc/ssh:/etc/ssh:ro

x-common-settings: &service-settings
  build: .
  image: opennebula:latest
  network_mode: host
  init: true
  <<: *common-volumes

services:
  init-container:
    command: init
    <<: *service-settings
  oned:
    container_name: oned
    command: oned
    <<: *service-settings
  scheduler:
    container_name: scheduler
    command: scheduler
    <<: *service-settings
  onehem:
    container_name: onehem
    command: onehem
    <<: *service-settings
  oneflow:
    container_name: oneflow
    command: oneflow
    <<: *service-settings
  onegate:
    container_name: onegate
    command: onegate
    <<: *service-settings
  fireedge:
    container_name: fireedge
    command: fireedge
    <<: *service-settings



